export const ChineseStudios: string[] = [
    'Haoliners Animation League',
    'LAN Studio',
    'B.CMAY PICTURES',
    'Red Dog Culture House',
    'Motion Magic',
    'Sparkly Key Animation Studio',
    'Shenman Entertainment',
    'Suoyi Technology',
    'Tianshi Wenhua',
    'Ruo Hong Culture',
    'Qingxiang Culture',
    'Wonder Cat Animation',
    'Sparkly Key Animation Studio',
    'Xing Yi Kai Chen',
    'L²Studio',
    'Tang Kirin Culture',
    'Foch Film',
    'CG Year',
    'Original Force',
    'Xiaoming Taiji',
    'Sharefun Studio',
  ]